# Generated by Django 5.0.2 on 2024-02-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='categories',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Smart Phones', 'Smart Phones'), ('Tablet', 'Tablet'), ('Smart Watch', 'Smart Watch')], max_length=200),
        ),
    ]
