# Generated by Django 5.0.2 on 2024-02-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_products_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='categories',
            field=models.CharField(choices=[('Smart Phones', 'Smart Phones'), ('Laptop', 'Laptop'), ('Tablet', 'Tablet'), ('Smart Watch', 'Smart Watch')], max_length=200),
        ),
    ]
